### ISSUE TITLE
Visualization from pattern

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#109]
**Is your feature request related to a problem? Please describe.**
Current visualization tool is based on the flow or gflow obtained from the `graphix.gflow.flow` or `graphix.gflow.gflow` functions, which may have different feedforward structure from the pattern itself.

**Describe the feature you'd like**
Add an option to visualize the feedforward structure according to pattern, not from flow or gflow. This can be done by obtaining layers from `Pattern.get_layers` and then constructing the arrows according to the feedforward part of measurement commands. Perhaps only consider either s or t feedforward for arrows as there may be too many of them.

**Additional context**
- also, it might be useful to change arrow type when nodes are not connected, as mentioned elsewhere by @d1ssk

**Comment by masa10-f** [comment]
> Perhaps only consider either s or t feedforward for arrows as there may be too many of them.

Comment on this part, s(X correction) is equal to g and t(Z correcion) is equal to Oddneighbor(g), so, in this context, arrows should be s signals(see thm. 2 in [Generalized Flow and Determinism in Measurement-based Quantum Computation](https://arxiv.org/pdf/quant-ph/0702212.pdf))

We can construct a function like `get_gflow_from_pattern` that collects all s signals or X corrections from pattern.
