### ISSUE TITLE
Python type hints

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#13]
**Is your feature request related to a problem? Please describe.**
enhancement request

**Describe the solution you'd like**
Add type hints to code

**Describe alternatives you've considered**
na

**Additional context**
e.g. https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html

**Comment by prakhar-kt** [comment]
@shinich1 Hi is this issue still open? Can I try to do this?

**Comment by shinich1** [comment]
Hi @prakhar-kt, 
yes it is! Please go ahead - I just created a branch for this issue which I believe you can check out locally :)
forking this repo would also be a good way, do choose whichever you feel comfortable.

**Comment by prakhar-kt** [comment]
thanks @shinich1 . I have started working on it
