### ISSUE TITLE
[Bug]: Some tests are broken if seed is changed

### ISSUE THREAD

**Issue by thierry-martinez** [TeamGraphix/graphix#130]
**Bug description**
The following tests are broken when tested with a different seed:
* `test_pattern.py::test_pauli_measurment_opt_gate`
* `test_pattern.py::test_pauli_measurment_opt_gate_transpiler`
* `test_pattern.py::test_pauli_measurment_opt_gate_transpiler_without_signalshift`
* `test_gflow.py::test_rand_circ_gflow`

**To Reproduce**
The failures in `test_pattern.py` can be observed by adding
```diff
+        rc.set_seed(25)
```
in the beginning of the method `test_pauli_measurment_opt_gate` (changing the `SEED` value in the beginning of the file will not change the behavior, since the seed value is overridden by other tests).

The failure in `test_gflow.py` can be observed by changing the value of `seed` in the beginning of the file.
```diff
-seed = 30
+seed = 25
```

**Expected behavior**
Changing the seed should not break the tests.

**Environment (please complete the following information):**
 - OS:  macOS 14.4.1 (23E224)
 - Python version: 3.11.8
 - Related module versions if applicable: numpy=1.25.2

**Additional context**
I noticed these failures in an effort to address https://github.com/TeamGraphix/graphix/issues/65

**Comment by EarlMilktea** [comment]
For `test_pauli_measurment_opt_gate*` tests, I also encountered it.

**Comment by masa10-f** [comment]
@shinich1 
Have you checked the `test_gflow.py::test_rand_circ_gflow` ?

**Comment by shinich1** [comment]
> @shinich1 Have you checked the `test_gflow.py::test_rand_circ_gflow` ?

I didn't have any problem on my side (I removed the skip command when trying). Somehow I haven't pushed it but we need to remove this line.
https://github.com/TeamGraphix/graphix/blob/19eb94cabccf0ca9f9ad2b765a2f2bfbf65bba93/tests/test_gflow.py#L510
