### ISSUE TITLE
Application of tensor-network MBQC simulation

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#136]
Add a .py file in `example` that illustrates the usage and application of TN simulation of MBQC, which contains:
- [ ] Detailed, step-by-step description of the TN construction and contraction in tensornetwork backend of graphix, and an example of how to tune the parameters for contraction path finding.
- [ ] Illustrate two exemplary applications of TN-based MBQC simulation which involves hundreds or thousands of qubits in the graph. Perhaps one of the following: i) simulation of many-body quantum systems ii) QML, iii) variational algorithm. 

**Additional context**

**Comment by shinich1** [comment]
> let me know if you want to have the code for the review @shinich1 
> 
> I can make a quick pull request for you

Hi @AbdullahKazi500, thanks for looking into this. If you create PR we can take a look and provide comment. 

As you noticed, this PR involves detailed reading of the implementation, as well as the documentation/paper of backend package.

**Comment by shinich1** [comment]
@AbdullahKazi500 thanks a lot for the PR!

While I appreciate neat rewriting of one of the existing examples, it is perhaps fair to say this looks almost identical to the qaoa example (from graphix usage standpoint), especially because energy calculation was done with state vector simulation result. 

Also - are you planning to do the first task of this PR? I believe this is the main part of this issue which is going to take time and requires prior experience with TN simulation. If not, in the interest of clarity for other hack participants, may I close your PR without merging?

**Comment by Barnald** [comment]
Hi @shinich1,
I was also working on this issue and reading the comments I would like to ask for a little clarification.

For the first part I went through the relevant implementation of graphix (tensornet.py, examples as well as their documentation respectively) and looked into other  modules too, which are used in graphix. For example I noticed that  quimb is used and that arguments can be passed which relate to contraction path finding in that module, so I tried to involve that in my implementation as well. Is this approach correct or have I misunderstood the problem?

For the second part, though I am aware that there is another example that is about QAOA, I was writing a QAOA algorithm for solving a max cut problem, that I believed would be different enough from the other example and could provide a possible case for application of TN MBQC. Should I change this direction?

Thank you for the answer in advance!

**Comment by shinich1** [comment]
hey @AbdullahKazi500 and @Barnald !

@AbdullahKazi500 - VQE looks good indeed, let me add a few requests to the PR so that it'll be compatible with the description of this issue, such as using TN contraction to get energy, problem size, potentially actually getting the optimum energy. Will comment on the PR, give me a little bit of time.

@Barnald  - For the first part, yes that is the correct approach! And second part - solving an actual problem would be a big difference indeed, especially with TN backend used for cost calculation and applied for larger problem size (hopefully the problem size is relatively large, such that it's rather difficult/slow to simulate with statevector), and that is a good case for TN-MBQC application.

**Comment by Barnald** [comment]
@shinich1 thank you for the answer!

**Comment by shinich1** [comment]
@AbdullahKazi500 @Barnald thanks for working on this issue!

Just to confirm regarding the hack. this issue involves 
i) descriptino of TN
ii) first example 
iii) second example
with more weight on i). 
Splitting the bounty (provided both PRs will be ready for merge, which I believe will happen soon) seems like a natural way, since each of you are solving the following part of the issue:
@Barnald  -> i) and iii)
@AbdullahKazi500 -> ii)
I believe it's fair for @Barnald to have more weight of the prize when splitting, 70%. Both of you will be on leaderboard, as far as I understand (will confirm with hack organizers). I hope this kind of arrangement make sense.

**Comment by Barnald** [comment]
@shinich1 That is great, thank you!

**Comment by shinich1** [comment]
@AbdullahKazi500 @Barnald assigned both of you to the issue. Organizer of the hack confirmed both of you will be on the leaderboard after merging PRs.
