### ISSUE TITLE
Tutorial and documentation style upgrade

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#137]
**Describe the feature you'd like**

1. Upgrade the sphinx theme to `sphinxawesome_theme` and ensure all introduction pages, tutorial, API docs and examples are shown properly. Make sure builds on readthedocs.org pass. Make sure the logo shows up on the top bar of the page, as in the current version (choose appropriate color for logo). the logo file is in docs/logo.
2. Update the `tutorial` page: incorporate latest version of the code, and make the page easier to follow. Use `pattern.draw_graph()` visualization tool as appropriate. Incorporate examples ([this](https://graphix.readthedocs.io/en/latest/gallery/qft.html#sphx-glr-gallery-qft-py) and [this](https://graphix.readthedocs.io/en/latest/gallery/noisy_mbqc.html#sphx-glr-gallery-noisy-mbqc-py) ) into tutorial page, and remove these examples.
3. update the `introduction to MBQC` and `introduction to LC-MBQC` pages to incorporate latest version of the code and make them easier to follow. Make sure to mention [this paper](https://arxiv.org/abs/2003.01664) which includes the general framework of MBQC with LC-decorated graph states, which our idea of pattern-based MBQC with LC is based on.

**Additional context**
Before preparing PR, please build the updated docs on your fork using readthedocs.org (login with you GitHub account and you should be able to see the forked repo to build; let me know if you have trouble configuring/building).

**Comment by Roshan-Thomas** [comment]
Hi, I am working on this issue, and I will create a PR shortly.
