### ISSUE TITLE
Optimize flow computation

### ISSUE THREAD

**Issue by EarlMilktea** [TeamGraphix/graphix#165]
**Describe the feature you'd like**

Refactor & optimize `gflow.py`.

We may need to resort to C++ or Rust bindings if `numba` doesn't work.

**Comment by EarlMilktea** [comment]
@shinich1 

I'm temped to try binding mainly because `numba` is not good at nesting pythonic data structures (such as `list`), which are inherently required to represent graphs.

**Comment by EarlMilktea** [comment]
In addition to baseline speedups (ex. faster for-loop), as flow/gflow algorithm repeatedly allocate/discard expensive data structures, we may be benefited by carefully managing/reusing working memories.

For that purpose, Rust would be better than C++.

**Comment by shinich1** [comment]
> @shinich1
> 
> I'm temped to try binding mainly because `numba` is not good at nesting pythonic data structures (such as `list`), which are inherently required to represent graphs.

Sounds good! binding with `Rust` seems to be the best way. 
Shall we try implementing in this repo, and once there's a PR, that would be a good place to discuss whether or not to move to a separate repo (as flow-finding algorithms and related linalg functions can be independent of graphix).

**Comment by EarlMilktea** [comment]
I'm pretty sure that flow/gflow calculator **CAN** be independent.
Do you want it to be in the same repo?

**Comment by shinich1** [comment]
independent repo souds good, here's new one: https://github.com/TeamGraphix/fastflow
I'm open to other naming ideas.. (nb `fastflow` seems to be available on pypi https://pypi.org/search/?q=fastflow&o=, though there's a [ML related paper with same name](https://arxiv.org/abs/2111.07677) )
