### ISSUE TITLE
Documentation CI takes very long

### ISSUE THREAD

**Issue by EarlMilktea** [TeamGraphix/graphix#212]
It typically takes ~10 min. per run even though its task is fairy simple.
Additionally, it seems that some kind of limit is exceeded during build process (see https://github.com/TeamGraphix/graphix/actions/runs/10834095505/job/30062455870 for the full output).

**Comment by shinich1** [comment]
This is due to the examples / sphinx-gallery, esp. QNN example.

**Comment by EarlMilktea** [comment]
I see. Let me check the bottleneck later.
