### ISSUE TITLE
Measurement pattern for error-corrected MBQC

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#48]
Implement the [fault-tolerant MBQC](https://arxiv.org/pdf/quant-ph/0510135.pdf) as a function or class that generates a `graphix.Pattern` object. Please implement it in a new file `graphix/topological.py`.

- Consider how the syndrome checks can be implemented as a linear sequence of MBQC commands and implement a generator so that users can obtain a measurement pattern by basic parameters such as code distance and the number of syndrome measurement rounds to perform.
- Decoding and correction will perhaps need to be a separate command to be in the MBQC pattern sequence, for which you may need to modify the Pattern and Simulator classes to accommodate these new commands. Feel free to import external modules to delegate the decoding task.

Please visualize the graph state using `Pattern.get_graph()` and `networkx` and see that the graph state indeed forms the [RHG lattice](https://arxiv.org/pdf/quant-ph/0510135.pdf).

Optionally, please implement some basic logical qubit operations such as single-qubit Clifford operations.

Please see our [contribution guide](https://github.com/TeamGraphix/graphix/blob/master/CONTRIBUTING.md) before starting, and do not forget to comment on this issue to show your interest. We are always happy to answer questions, so do not hesitate to ask on this page.

Thank you for your interest, and good luck!

**Comment by shinich1** [comment]
@AbdullahKazi500 as discussed on the other issue page, we need to wait until there's PR ready to merge to assign an issue - please have a go at working on this, we're looking forward to your PR.

**Comment by Gopal-Dahale** [comment]
@shinich1 I am trying to understand the graphix library, especially the QAOA example. Qiskit also has a similar [example](https://learn.qiskit.org/course/ch-applications/solving-combinatorial-optimization-problems-using-qaoa). There, they use an optimizer for optimizing the parameters of the quantum circuit and then get the desired state. I am unable to understand how this works in graphix?

**Comment by shinich1** [comment]
@Gopal-Dahale the qiskit example uses `scipy.optimize.minimize` to do the classical part of the optimization. The same would work for Graphix - we define a function to generate a pattern from parameters and sample the result, and then put the function into `minimise` function. Since the shape of the circuit (pattern) is always the same in every step, #45 would help speed this process up because we would then only need to compile pattern once.
