### ISSUE TITLE
arbitrary initial state

### ISSUE THREAD

**Issue by shinich1** [TeamGraphix/graphix#53]
**Is your feature request related to a problem? Please describe.**
Currently, graphix does not assume arbitrary initial state for the MBQC. This is not a problem (still universal, just like real quantum hardware) but it would be a good feature to have, to test out MBQC with small toy models

**Describe the feature you'd like**
An option to simulate with arbitrary input state. For this, we would need:
- an option to keep the input nodes during the `Pattern.perform_pauli_measurements()`. Otherwise input nodes will be considered fixed `|+>` states and be preprocessed, making it difficult to simulate with arbitrary input state.
- an option to use arbitrary input statevector in `StatevectorBackend`.
- similar option for TN backend.

**Additional context**
na

**Comment by mgarnier59** [comment]
I will work on that. I think it also requires modification of the preparation MBQC command N so as to allow user-defined preparations.
