### ISSUE TITLE
Add support for python 3.11?

### ISSUE THREAD

**Issue by king-p3nguin** [TeamGraphix/graphix#90]
Python 3.12.0 was just released today (Oct. 2, 2023), and it might be a good time to add support for Python 3.11.

**Comment by shinich1** [comment]
yes perhaps a good idea! we can consider stopping support for 3.8 because newer versions of numpy stopped supporting it (throws error when trying to install all dependency by `python setup.py develop` with py3.8 because of that)

**Comment by king-p3nguin** [comment]
OK, I will make a PR on this.
