### ISSUE TITLE
Pauli Flow finding algorithm

### ISSUE THREAD

**Issue by masa10-f** [TeamGraphix/graphix#93]
**Is your feature request related to a problem? Please describe.**

Graphix incorporates both flow and gflow finding algorithm. I think that the implementation of the Pauli flow finding algorithm would enhance its utility.

**Describe the feature you'd like**

Following the algorithm described in EPTCS 343, 2021, pp. 50-101.

**Additional context**

na

**Comment by masa10-f** [comment]
I paste the link to the [paper on arXiv](https://arxiv.org/pdf/2109.05654.pdf)

**Comment by d1ssk** [comment]
I benchmarked 'find_pauliflow()' using patterns which were transpiled from random circuits and removed Pauli measurements, as shown in the following code. The computational complexity indicated in the [paper](https://arxiv.org/abs/2109.05654) is O(N^5) with respect to the number of nodes N, but I understand this is a theoretical upper bound, and typically, as shown in the results below, it can be achieved with much less complexity.
![output](https://github.com/TeamGraphix/graphix/assets/52164693/4049f358-e7f3-4ce0-8ba3-239ce9e33bae)
[pauliflow_benchmark_py.txt](https://github.com/TeamGraphix/graphix/files/15260255/pauliflow_benchmark_py.txt)
