### ISSUE TITLE
Flow and Gflow Checker

### ISSUE THREAD

**Issue by masa10-f** [TeamGraphix/graphix#99]
**Describe the feature you'd like**

A function that determines whether a given (g)flow is a correct (g)flow or not based on the definition.

**Additional context**

It can be useful for a graph-based generator and ZX-calculus-based backend, which will be introduced in the future.

**Comment by pafloxy** [comment]
Hello! it seems a good idea :)  how do you plan to proceed about it ? 
I think it can be most conveniently checked by building two matrices one for the Gflow (say $\mathtt{F}$ ) another for the odd neighbourhood of Glfow (say $\mathtt{O} \ : \ (\mathtt{A}_G \  \mathtt{F}^T)^T$ , where $\mathtt{A}_G$ is the adjacency matrix )  and then simply ensuring that those matrices are lower-triangular. Depending on the measurement plane we might need to check the diagonal elements as well but that won't add up to any further complicacies. I can put in more details about the calculation involved if you want, let me know what you think ;) 
*PS:* The linear algebra must be in $GF2$                                                                             

Also what do you mean by a 'graph-based generator'  ?

**Comment by pafloxy** [comment]
Hello! it seems a good idea :)  how do you plan to proceed about it ? 
I think it can be most conveniently checked by building two matrices one for the Gflow (say $\mathtt{F}$ ) and another for the odd neighbourhood of Glfow (say $\mathtt{O} \ : \ (\mathtt{A}_G \  \mathtt{F}^T)^T$ , where $\mathtt{A}_G$ is the adjacency matrix )  and then simply ensuring that those matrices are lower-triangular. Depending on the measurement plane we might need to check the diagonal elements as well but that won't add up to any further complicacies. I can put in more details about the calculation involved if you want, let me know what you think ;) 
*PS:* The linear algebra must be in $GF2$                                                                             

Also what do you mean by a 'graph-based generator'  ?

**Comment by masa10-f** [comment]
Thanks for your comment and sorry for the late reply.
I understand your idea. I didn't think much about the implementation 
when I made this issue. Your proposal seems good, so I plan to follow it for implementation. Once I've pushed the changes, would you review my implementation?

> Also what do you mean by a 'graph-based generator' ?
The `graph-based generator` here indicates `graphix.generator.generate_from_graph` that generates a pattern from a graph with measurement planes.

**Comment by pafloxy** [comment]
Sure ! I will be glad to help
